[package]
name = "trace-rs"
version = "0.1.0"
authors = ["Chris Statkiewicz <christopherstat@protonmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0.3"
specs = "0.14.3"
yaac= { path = "yaac", version = "0.1.0" }
